version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "posts"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1iq314qfm1lao"
s3_prefix = "posts"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
