version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "threads"
s3_bucket = "versus-bucket"
s3_prefix = "threads"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"

