AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: versus backend function

Globals:
  Function:
    Timeout: 5

Resources:
  ThreadsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: threads/bin
      Handler: threads
      Runtime: go1.x
      FunctionName: "threads"
